name: build react app image and push to github packages
on:
  push:
    paths:
      - 'counter-app/**'
  workflow_dispatch:
env:
    GITHUB_USER: ishtiaqsamdani007
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: counter-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        # cacahe node_modules to speed up build
        
     
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            npm install
            
      - name: Build application
        run: |
            npm run build

      - name: run tests
        run: |
            npm run test

              
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ env.GITHUB_USER }}
            password: ${{ secrets.GIT_TOKEN }}
    
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: ghcr.io/${{ env.GITHUB_USER }}/react-package:${{ github.sha }}
      - name: Deploy to EC2 from github packages
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AWS_PUBLIC_IP}}
            username: ${{ secrets.AWS_USER }}
            key: ${{ secrets.AWS_PRIVATE_KEY }}
            script: |
                docker login ghcr.io -u ${{ env.GITHUB_USER }} -p ${{ secrets.GIT_TOKEN }}
                docker pull ghcr.io/${{ env.GITHUB_USER }}/react-package:${{ github.sha }}
                docker logout ghcr.io

            
        