name: build react app image and push to github packages
on:
  push:
    branches:
      - main  
  workflow_dispatch:
env:
    GITHUB_USER: ${{ github.actor }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        # cacahe node_modules to speed up build
        
     
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i
        
      - name: ls
        run: ls -la
      - name: Build application
        run: npm run build

      - name: run tests
        run: npm run test

      - name: Build docker image
        run: docker build -t ghcr.io/username/counter-app:latest .

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Packages
        run: docker push ghcr.io/username/counter-app:latest


            
        