name: build react app image and push to github packages
on:
  push:
    branches:
      - main  
  workflow_dispatch:
env:
    GITHUB_USER: ${{ github.actor }}
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: ls
        run: ls -al

            
        