name: build react app image and push to github packages
on:
  push:
    branches:
      - main  
  workflow_dispatch:
env:
    GITHUB_USER: ishtiaqsamdani007
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        # cacahe node_modules to speed up build
        
     
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: counter-app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            cd counter-app
            npm install
        
      - name: ls
        run: |
            cd counter-app
            ls -la
      - name: Build application
        run: |
            cd counter-app
            npm run build

      - name: run tests
        run: |
            cd counter-app
            npm run test

              
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ env.GITHUB_USER }}
            password: ${{ secrets.GIT_TOKEN }}
    
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
            context: ./counter-app
            push: true
            tags: ghcr.io/${{ env.GITHUB_USER }}/react-package:latest

            
        